### ISSUE TITLE
Storm Drain Storage Unit

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1048]
Build Storage units with plugin

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 

Hi JJ,

You can start on this one.  It is well documented in the EPA SWMM Gui so you should have pretty excellent info there.

Don't add any of those bad table editors on this one.  Let's figure out a better way to build tables.  Your method doesn't have a copy paste capability and that makes them very hard to use.

Add it to the Node group.

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi @rpachaly @FLO-2DJJ 

Hi All,

I'm trying to anticipate what sort of Data a FLO-2D storage unit would need.

Some of the storage units are closed like a cistern and some are open like a basin.  We don't want to add an open storage unit to the grid, but I suppose we could still use an offsite storage unit that could interface with rainfall.

For example, North Mesa has a basin that is south of the project but interfaces with our channel at a culvert.  We could model it as a storage unit instead of a basin that is built into the grid.

We need to identify which data will be used on a FLO-2D storage unit system.  Maybe we can have a meeting about this next week.

**Comment by FLO-2DNoemi** [comment]
@FLO-2DJJ  I reviewed the SWMM manual and GUI for the creation of the storage units (SU) data and I am adding below my comments. We can discuss this anytime if it is needed. 

Let's think about SU as an inlet with additional storage capacity. A SU is very similar to a manhole but with water storage capacity. To calculate the storage capacity the SU needs tabular data with 2 columns: Depth of water vs Area or a functional curve that defines the stage-storage condition.

The image below shows the data in red that is required to simulate SU in FLO-2D:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424558/233836fe-725e-4e81-a761-2f3795eac66b)

From the windows above:

1. Name, X- and Y- coordinates are fields that all inlets should have this data. Nothing to add.
2. Inflows refer to external inflow conditions that enter the SD system. This is already implemented for inlets, see image. We already reviewed the external inflow tables when the external inflow was created for inlets. I anticipate that external inflow received by an SU should be identical to an external inflow received by any other inlet type.  I will review the fields one by one, but I can anticipate there is nothing additional for SU external inflows.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424558/d316f79f-b26b-466c-b63c-2b46651cbf50)

3. Invert Elevation,  Max Depth and Initial Depth, there should be no difference with what is already implemented in the elevation field for inlets.

4. Infiltration through the bottom of the SU: we may need to use the infiltration calculation (GREEN-AMPT) from SWMM, the reason is that this infiltration is calculated through the bottom of the SU, and this is part of the Storm Drain layer, it is no part of  the surface layer. @FLO-2DKaren let's discuss this anytime during this coming week so we can provide details to JJ.
5.  Storage Curve, Functional Curve data and Tabular curve is the data that characterize the SU. This data constitutes the core of this task. This is the specific data for SU.

**Comment by FLO-2DJJ** [comment]
@FLO-2DNoemi, @FLO-2DKaren 
Thanks for the additional information.
Let's have a meeting to clarify some details.
In particular, but not exclusively:

- Infiltration through the bottom of the SU (Point 4. in Noemi's comment above).
- Inflows. Already implemented for Inlets (but without the 'Dry Weather' and 'RDII' tabs of EPA SWMM) (Point 2. in Noemi's comment above).
- Do we need a 'Storage Units' tab in 'Select Components from shapefile layer'?
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/15ea44f7-4b3a-48c5-b2fd-e1d1c281c757)

**Comment by FLO-2DJJ** [comment]
These are some sub-tasks of this issue so far (done or to do):
1. [ ] Import groups associated with [STORAGE]: [CURVES], [TREATMENT], [DWF], [TAGS], [COORDINATES] (to internal memory).
2. [ ] Solve conflicts reading [COORDINATES] with inlets, junctions, and oufalls when [STORAGE] is considered.
3. [ ] Skip bad [TIMESERIES] data (collateral bug).
4. [ ] Export SWMMFLORT: message when RT with no inlet associated with node (collateral improvement).
5. [ ] Add [CURVES] to 'files saved dialog' at the end of "Export SWMM.INP...".
6. [ ] Catch errors in [INFLOW] group related to unknown storage units (importing/exporting .INP data).
7. [ ] Add 'swmm_other_curves' table and layer (may not be shown in layers panel).
8. [ ] Add 'description' to reading of [CURVES].
9. [ ] Read/write .INP [CURVES] group.
10. [ ] Read [PATERNS] group and create swmm_inflow_paterns.
11. [ ] Skip storage units when reading [STORAGE] that do not have coordinates.
12. [ ] Skip not used or bad data from SWMM.INP in all groups related to Storage Units (during read/write).
13. [ ] Catch/correct data when loading time series in Inlets and Outfalls dialogs from .INP (somehow EPA SWMM writes incomplete rows) (collateral bug).
14. [ ] Check [SUBCATCHMENTS] when importing INP: Show warning that inlets (with prefi]x "I" or "i") were skipped if there are [SUBCATCHMENTS] (collateral).
15. [ ] Add "user_swmm_storage_units" table and layer.
16. [ ] Import SWMM.INP: Import [STORAGE] into user_swmm_storage_units layer: 'Create new Storm Drains' option.
17. [ ] Import SWMM.INP: Import [STORAGE] into user_swmm_storage_units layer: 'Keep existing and complete' option.
18. [ ] Design Storage Units dialog.
19. [ ] Code class for Storage Units dialog.

**Comment by FLO-2DNoemi** [comment]
Hi @FLO-2DJJ 

Can we already start testing this task in the current plugin from GITHUB?

**Comment by FLO-2DJJ** [comment]
Wait until I finish a main Storage Units dialog (to be called from the Nodes list in the Storm Drains widget). What I have already done might change as the code progresses.
The branch I uploaded is intended as a backup which will be converted to a pull request when ready for your testing and approval.

**Comment by FLO-2DJJ** [comment]
Make use of the CurveEditorDialog to be defined in issue #1169

**Comment by FLO-2DJJ** [comment]
Here you have a video of what I already done for Storage Units in the plugin:

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/e9239132-13a2-49d6-b4b5-28d76ade094f

Please, look at it.

**Comment by rpachaly** [comment]
Hi JJ, 

It is looking really good!

**Comment by FLO-2DKaren** [comment]
Hi JJ,

I found a few issues.

1. I couldn't finish your video.  Sorry It stopped when you were talking about green ampt.
2. How do you fill in the grid attribute?  Do you do it manually.  I thought it might fill in when I used schematize.
3. I guess we do need a shapefile assignment like the others.  I have a test project for you.
4. I think you need to fix the auto assign link for weir, pump, and orifice.  I got a video here:

I'm at a loud hotel so I didn't record sound.



https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/692d2c54-2d2e-4e11-9b54-138848c0aa1e

**Comment by FLO-2DKaren** [comment]
JJ,

Here is my test project.

@rpachaly 
Hi Robson,  You might want this advanced test project too.  It's a nice one.

[Lesson 1_v1.0.0.gpkg.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/14518266/Lesson.1_v1.0.0.gpkg.zip)

**Comment by FLO-2DJJ** [comment]
Thanks Karen,

I'll check them out.

I may make points 2, 3, and 4 as new issues after I see their complexity.

Do you have the .DAT and SWMM files for this project? Some of the issues
could be pinpointed and corrected during their loading.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DJJ** [comment]
I know that the DAT files and SWMM files can be created from the plugin but
I just want to know if the original swmm.inp is created from EPA SWMM or
other source.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DJJ** [comment]
Thanks, I'll check them out.

**Comment by FLO-2DJJ** [comment]
Completed. 
This related issue will be addressed next: **Add Storage Units to 'Select components from shapefile layer'** #1228
