### ISSUE TITLE
Levee Guidelines

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1057]
This is a task to update the levee guidelines.  This is a District Task.

**Comment by FLO-2DKaren** [comment]
The levee guidelines need a lot of work so we should probably identify what FCDMC needs before we try and organize the levee guidelines.

**Comment by FLO-2DKaren** [comment]
Maybe we can meet with someone to set some goals so we know how much effort we can apply to this.

**Comment by FLO-2DKaren** [comment]
- [ ] Update images from GDS
- [ ] Add equation numbers
- [ ] Modify wall guidelines to the actual FCDMC method
- [ ] Ask Elizabeth what they want to see in the manual

[Levee, Dam, and Wall Breach Guidelines.docx](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/14605134/Levee.Dam.and.Wall.Breach.Guidelines.docx)

**Comment by FLO-2DKaren** [comment]
Load projects here:

**Comment by rpachaly** [comment]
I removed all GDS images and references. Also, I removed all references to Mapper and changed it to Rasterizor and MapCrafter. Equation numbers were added and the text adjusted.

[Levee.Dam.and.Wall.Breach.Guidelines_Rob.docx](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/14617028/Levee.Dam.and.Wall.Breach.Guidelines_Rob.docx)

I did not update the wall guidelines to the actual FCDMC method because I'm not acquainted with the method. 

I let a comment on the document on the "A New Friction Slope Equation" section. Jim sent me a few months ago this document
[Reservoir Routing and Ponded Flow.docx](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/14617061/Reservoir.Routing.and.Ponded.Flow.docx) and it is different from the guidelines. I believe that this document is correct and the guidelines are outdated. Can you confirm this Karen?

**Comment by FLO-2DKaren** [comment]
Jim and I will check that out.

**Comment by FLO-2DKaren** [comment]
This is what I got from a meeting with Stephanie.

SUBCONSULTANT will make the following modifications to the Levee Manual
https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1057
a. Update the Levee, Dam, and Wall Breach Guidelines Manual and FLO-2D Reference Manual Levee Section.
i. Review the data input manual and guidelines to check for compatibility.
ii. Review switches and data columns to correct potential errors and illustrate correct data development methods.

This last one is the one Stephanie wanted.

**Comment by FLO-2DKaren** [comment]
Complete Uploaded here
https://flo-2d.sharefile.com/d-s00d37118775a4564a37fb757c327830e
