### ISSUE TITLE
Full path for external layers

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1083]
Can we use the full path for these instead of the truncated path?  This will also be important for our mapcrafter and rasterizor layers.

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/fe65fd81-df8d-4d9e-bfc1-450bbfd8963a)

**Comment by rpachaly** [comment]
Maybe the best solution here is to add user layers into the geopackage. Like a button for adding layers into the project or something. Then everything will be on the same place. It will be good for sharing data.

However, I'll need to change the way of checking old gpkgs.

**Comment by rpachaly** [comment]
@FLO-2DKaren What do you think?

I've changed the way of checking if a geopackage is outdated. Now, it checks if all tables are present and not only the number of tables. I can add a button for adding user layers directly into the geopackage. Since the .qgz file is inside the gpkg, all user styles will be saved.

**Comment by FLO-2DKaren** [comment]
From meeting:
When you hit the save button, it asks user to add layers to the geopackage?

**Comment by FLO-2DKaren** [comment]
I think this is invalid now so I'll close it.
