### ISSUE TITLE
Storm Drain Node Outside of Grid

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1099]
It is OK for a storm drain node to be outside of the computational domain so long as it is a junction.  
We need to modify the code so that this can happen.

North Mesa INP has an example but it is a huge project so I can probably just edit another project to show this.

**Comment by FLO-2DKaren** [comment]
I'm going to try and answer your items here.

1. We need to check to make sure those are filled when the Schematize button is applied.  Mine were empty today.
1. If statement to skip if point is not within a grid element.
2. I thought it was already using the point but if not, that's probably a good way to do it.
3. Use zoom to line??
4. I don't think so but we'd need to test it anyway.

Is this worth it or should we force people to keep their data inside the grid????

@FLO-2DNoemi 
Can you weight in on this?

**Comment by FLO-2DKaren** [comment]
Finish in 2024 but not by June.
Karen add a test project.

**Comment by FLO-2DNoemi** [comment]
We need inlets and outfalls to be inside the grid because they exchange
water with the surface.

Junctions do not exchange water with the surface so they can be outside of
the domain for all configurations, they also can have an assigned
hydrograph as a BC, this is flow collected from an upstream basin that
flows into the project domain.

In other words, we need to allow junctions to be located outside of the
grid. This should be an easy fix to the plugin, some comments that I think
will help:

- There is no connection between junctions and grid surface elements.
Junctions are not connected with any feature in the surface layer.
-  Junctions are not in SWMMFLO.DAT, SWMMOUTF.DAT or SWMMFLORT.DAT, only in
the SWMM.INP file.

The current plugin checks if the SD features are inside the project domain,
we need to remove junctions from this check and allow them to be outside
the grid domain. The only SD features that need to be inside the project
domain are inlets (SWMMFLO.DAT) and outfalls (SWMMFLORT.DAT).   We should
be able to include this change in the plugin quickly.

@Karen OBrien ***@***.***>, I know JJ is currently working on
something else. I think @Robson Pachaly ***@***.***> might be able
to fix this by June.


Can we have an outfall that discharges out of the domain? Yes, this could
be an option,  but only in those cases where the outfall flow is not
discharging back to the surface, in other words when the outfall  switch
OUTF_FLO2DVOL  (SWMMOUTF.DAT) is equal to 0, this means, the flow is
discharging off the system and not back to the surface, in other words, the
outfall discharge is removed from the storm drain system. This is not
important and I think we can revisit this after June.

Noemi

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi We already discussed it in a meeting.  It isn't going to be finished by this week but it will be done by June.

**Comment by FLO-2DNoemi** [comment]
Ok, thanks for the update.

**Comment by FLO-2DKaren** [comment]
This isn't working.  See Test Video.  I tested this on the master branch and the Vertices branch so if you see something wrong off, it's because the Video is done on the Vertices branch.

Test Project
[Test Project with nodes off grid.zip](https://github.com/user-attachments/files/15571232/Test.Project.with.nodes.off.grid.zip)


https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/0c204c90-518b-4110-8b5b-51b9aa5475d6

I assumed this would be finished and working.  In order to get it done by June 30, I'm assigning it to Robson.

**Comment by FLO-2DNoemi** [comment]
It will be good to have this for June 30 but if the fix is difficult to
implement we can leave for the next release. this is not a critical feature.

**Comment by rpachaly** [comment]
Hi all, 

Storage Unit, can it be outside the grid? It could be used the same way as a junction (hydrograph assigned).

**Comment by rpachaly** [comment]
And what about pumps, weirs and orifices?

**Comment by rpachaly** [comment]
See this video:

https://flo-2d.sharefile.com/d-sa105b88dd12a491a881d8fa161af66dd

I'll be working to apply the same process to the import from INP

**Comment by FLO-2DKaren** [comment]
It would probably be odd to have one pump, orifice, or weir cross a boundary but I think we should add them.

The storage unit not being part of the ID of the conduit fields should not prevent it from being added to the storage unit layer.  That doesn't make sense.  Something is preventing that data from being written to the layer.  

Send me your project and I'll see if I can test some other configurations.  I don't want to have those fields filled in the link layers.  It is really hard to build that data manually.  Its one reason the AutoAssign tool is so important.  

There has to be some other issue.  I'm sure we'll figure it out.

**Comment by rpachaly** [comment]
Here are the projects that I'm using

https://flo-2d.sharefile.com/d-s2eecc1ac28a64d4f915e65e1a449adb2

https://flo-2d.sharefile.com/d-s69be6e7051f4415b8720932854540719

**Comment by FLO-2DKaren** [comment]
I will modify some parameters to see if something is preventing those storage units from loading.  If you already know why they are failing that would save time.  

I don't want to use the conduit connector fields.  I would prefer that we eliminate those all together.

**Comment by rpachaly** [comment]
It is not the SU that is falling, it is the conduit that I'm not able to figure out how to recognize it without knowing the pipes connects. But we're going to figure out a way of doing it.

**Comment by FLO-2DKaren** [comment]
Robson and I had a meeting and we determined a way forward.  There were no errors just needed to modify the storage unit processing tool.

**Comment by FLO-2DNoemi** [comment]
Thanks for the update.

**Comment by rpachaly** [comment]
It is ready! On https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1377/. Check the videos bellow. 

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/8e3cfc13-fe0e-4ba9-b13f-81193060d81c


https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/52f2b244-3fdd-4c98-95c1-53a242cb3476

**Comment by FLO-2DKaren** [comment]
ok nice  I think this is what we want I think.  I want Elizabeth to watch the two videos because we just had an email exchange with her and she'll want to see this.

@FCDMC-SPB

Hi FCDMC.  Here's the nodes  and links outside domain and how we are addressing them. 3 good videos showing the testing with different projects.

**Comment by FLO-2DKaren** [comment]
@FCDMC-SPB 
Hi Elizabeth,  Download them if they won't play.  Or try another browser.  I use chrome and I also have that issue sometimes.
