### ISSUE TITLE
MapCrafter Layers

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1106]
Recongnize that layers come from MapCrafter and group them accordingly.

We can also do something in MapCrafter so we use the geopackage instead of the rasters???  Something to look into.

**Comment by rpachaly** [comment]
In order to recognize a MapCrafter layer efficiently, we need to specify a raster metadata when it is created. See this question and answer on stack overflow https://gis.stackexchange.com/questions/214247/set-raster-metadata-in-gdal-and-view-in-gis-software

The best approach is to add a FLO-2D MapCrafter label using the TIFFTAG_IMAGEDESCRIPTION when a raster file is created on MapCrafter. Then, when adding to the FLO-2D Plugin geopackage, it recognizes the metadata and group it accordingly. However, I believe that this is an issue for MapCrafter. 

Let's implement it or wait for an update on MapCratfer?

**Comment by FLO-2DKaren** [comment]
Hi Robson,

Implement it as you need it but we'll wait to do a release until we need to update MapCrafter.  We can just use it internally until then.

**Comment by rpachaly** [comment]
Ok! Today I'm focused on the BC Editor, by tomorrow I'll try to have this completed.

**Comment by FLO-2DKaren** [comment]
Well tested and OK
