### ISSUE TITLE
Test Projects

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1121]
This first project will allow for multiple domain interaction.  It comes with some videos.

Video Links:

1st Video is a single shared boundary between two domains. https://www.youtube.com/watch?v=-oxu7ZzUKlk
2nd Video is two shared boundaries. https://www.youtube.com/watch?v=OHt4w6_mAYs
3rd Video adds the channels outflow to the boundary. https://www.youtube.com/watch?v=9RWwCu5VUT8

**Comment by FLO-2DKaren** [comment]
Projects are here.  I started uplaoding 6pm Ny time on Monday night.  Should be done by Tuesday Morning
dec 18 2023

https://flo-2d.sharefile.com/d-sb2ec6ab58f1b425f8d6b5ef2a99deff9

**Comment by FLO-2DKaren** [comment]
This project has a boundary with a tide condition.  I think.  Noemi might have made the tide with GDS.

https://flo-2d.sharefile.com/d-se8c125dacdb2467283834bce3d9b2fca

**Comment by FLO-2DKaren** [comment]
If you need any others, let me know.  Channel outflow nodes are only set to the last left bank node.

**Comment by FLO-2DNoemi** [comment]
Yes, I created the Stage Time (ST)  boundary condition (BC) using GDS.  Let
me know if we need to discuss the format.  Let's change how we write the ST.

Right now, we write the following for each boundary cell with a ST BC:

*OUTCHAR = ‘N’ NOSTA NOSTACFP  *
*OUTCHAR = ‘S’ STA_TIME(J) STA_STAGE(J) J=1  *

* NOSTA=*  is the grid element with a stage-time relationship.
*NOSTACFP=*  is the floodplain (0) or Channel (1) identifier.
*STA_TIME*=  array of time intervals (hrs) for the grid element stage-time
relationship.
*STA_STAGE*= array of WSE (ft or m) for the stage-time relationship

Example:

*N              9             0 *
S              0            -0.886
S              0.25         -0.82
S              0.5          -0.755
S              0.75         -0.689
S              1            -0.656
S              1.25         -0.591
S              1.5          -0.558
*N              35             0*
S              0            -0.886
S              0.25         -0.82
S              0.5          -0.755
S              0.75         -0.689
S              1            -0.656
S              1.25         -0.591
S              1.5          -0.558

The issue is that we are *repeating the S lines for each grid element that
contains a tide regardless if the tide condition is the same*, this makes
the file huge and we spend extra time reading and writing the same ST BC
for each cell. The intention is to change the format of this BC, and write
the ST only one time. We can write the N lines and then the BC.

Example of two ST BCs:


*N              9             0*

*N              35             0*

*N              47             0*

*N              52             0*
*N              150             0*
S              0            -0.886
S              0.25         -0.82
S              0.5          -0.755
S              0.75         -0.689
S              1            -0.656
S              1.25         -0.591
S              1.5          -0.558

*N              11             0*

*N              45             0*

*N              57             0*

*N              62             0*
*N              175             0*
S              0            0.38
S              0.25         0.52
S              0.5          1.755
S              0.75         0.89
S              1            0.75


Noemi

**Comment by rpachaly** [comment]
Thanks for recommending those videos, Karen. It is more clear for me now how to set up the multiple domain and the outflow conditions for multiple domains. But it is a little complicated, isn't it?

I think that these models are sufficient for the testing that I want to do. Thanks again. 

Noemi, we can use the same approach as the Time Series on the Inflow BC. Two tables, one with the grid element and the related tide identifier and another table with the tides conditions. I'm going to start the import OUTFLOW.DAT on the new BC Editor and I'll get more acquainted with the ST Boundary Condition. If other idea comes up, I'll let you know.
