### ISSUE TITLE
Add Inflow Error

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1138]
It seems like the inflowfid is not set correctly and its causing an error when the export is made.

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/a7107f6e-a0a8-4ecb-9c2a-405ddd6f4924)

**Comment by FLO-2DKaren** [comment]
Ignore this error.  Bad Boundary in that gpkg file.

**Comment by rpachaly** [comment]
Weird error. The bc_fid is the ID on the Boundary Conditions Points shapefile and the inflow_id is the ID on the inflow table. The ID's look correct in the video. Maybe an error on the schematize button.

**Comment by rpachaly** [comment]
I fixed this bug by modifying a TRIGGER in the geopackage structure because now the inflows and outflows are schematized separately. Therefore, if the geopackage was already ported, it may raise the same error again. The geopackage must be ported again from the old geopackage. Be aware of this when testing.

I'll fix all the bugs and then do a more complete testing before handing it back to you.

**Comment by FLO-2DKaren** [comment]
I guess we wait for it to be an issue again in the future.  I'll watch the video again so I can test it too.

**Comment by FLO-2DKaren** [comment]
I think this one is OK.  It passed a more complex test.
