### ISSUE TITLE
Add checks on the python code

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1176]
1 CHANNEL WIDTH ERROR

- [x] 1.1 Cross-section is wider than the distance between two left and right bank 

- [ ] 1.2 Area on the bank elements is less than 5%

2 RIGHT BANK ERROR

- [ ] 2.1 Right bank is inside the two bank lines

3 BOUNDARY CONDITION ERRORS

- [x] 3.1 Outflow last cross-section must be lower than adjacent upstream neighbor by 0.1 ft

- [x] 3.2 Upstream inflow boundary must be positive slope in the downstream direction

**Comment by rpachaly** [comment]
@FLO-2DKaren 

Does 3.1 raise an error on ERROR.CHK? I couldn't raise this error even modifying the data.

**Comment by rpachaly** [comment]
Karen, would you mind explaining again the "area on the bank elements is less than 5%, you get another too narrow flag"?

**Comment by FLO-2DKaren** [comment]
Hi Robson,

Here is the test project you asked for.  You will need to resample the elevation before you interpolate and export.  I had to build some errors into the elevation file.  See that there are 2 elevation files.  Use the one that says Error Inducing.

https://flo-2d.sharefile.com/d-s169719d665e442cabad0dab16507eb72

**Comment by FLO-2DKaren** [comment]
Hi Robson,  I will describe the 3 issues here.  This topic defines when a channel needs to expand into another bank element. 

1. The left and right bank is different elevation.  Even if a channel is not as wide as a grid element, if the cross section left and right elevation are different, it needs to expand into another grid element.  Left bank grid element elevation is reset to the left top of bank in the cross section data.  Right bank grid elevation is reset to the right top of bank elevation in the cross section data.  This happens at runtime and flopro.exe does it automatically.
2. The interpolated cross section is wider than the distance between the left and right bank grid element centroids.  So that is the left top of bank to the right top of bank in the cross section data.
3. The channel shares a space on the left and right bank.  The overland routing uses part of the grid element and the channel uses part of the grid element.  the exchange occurs on the left over bit.

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/408b01a4-fd62-4d8f-a21e-dd2b76b83d15)

Here is a video
https://flo-2d.sharefile.com/d-s72e7fa0ce384486a8fe274d10ea59958

**Comment by FLO-2DKaren** [comment]
> @FLO-2DKaren
> 
> Does 3.1 raise an error on ERROR.CHK? I couldn't raise this error even modifying the data.

Set the low elevations in xsec.dat to 744.  Make sure to get all of them.  You can't do only one.

**Comment by rpachaly** [comment]
My current code is working pretty well for most cross-sections aligned north-south & east-west (matching FLO-2D ERROR.CHK). However, some of the inclined cross-sections do not match the ERROR.CHK. Let's discuss two cross-sections:

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/2743e3e2-607e-4c85-8fb0-039c79044ade)

FLO-2D Engine flags area error and my code do not flag
channel top width = 198.4
channel surface area = 198.4 * 30 = 5952
n grid = 7 (intersects the cross-section)
grid area = 30 * 30 * 7 = 6300
ratio = 0.94

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/4448838c-7da5-4ed8-8150-6c828f7da83b)

My code flags area error and FLO-2D Engine do not flag
channel top width = 171.6
channel surface area = 171.6 * 30 = 5148
n grid = 6 (intersects the cross-section)
grid area = 30 * 30 * 6 = 5400
ratio = 0.953

I think that the error is related to how I calculate the areas.

**Comment by FLO-2DKaren** [comment]
Let's ask Jim for how he calculates the error.  I'll do it via email.

**Comment by FLO-2DKaren** [comment]
I was able to get the check to work so I'm going to close this but I found some issues that I will be reporting on a new issue.
