### ISSUE TITLE
Path error while loading a Rating Table (Storm Drain)

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1186]
Needs to adjust the path. It works on the second time that I tried to load the rating table.

**Comment by FLO-2DKaren** [comment]
This uses the swmm path so it will use the last path that is saved into the swmm path.
So we need to update the swmm path when we load the rating table file and update the swmm path when we export the dat files because if you don't, you run the risk of saving your swmm.inp to the wrong path when you export a project.

**Comment by FLO-2DKaren** [comment]
If you could fix both issues, that would be very cool.  I don't think it's hard but it would still be awesome.

**Comment by rpachaly** [comment]
Fixed the error on importing the rating table. 

Now when exporting SWMM.inp it reads the export folder and not the SWMM path. This will avoid exporting the SWMM.inp to the wrong path. 

It is on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1188https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1188

**Comment by FLO-2DKaren** [comment]
This is great. I hope by the end of this year we can do a quick run on all models. This type of work will help to that.

**Comment by FLO-2DKaren** [comment]
Tested and OK
