### ISSUE TITLE
Channel Review Check

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1208]
Hi Robson,

Check this video out.
https://www.youtube.com/watch?v=x1QEP2ggYT0

13:00 min: I intentionally set the error.  The right bank does not cross the cross section.
14:00 min is where I put the cross section and the left bank crossing in the wrong spot so the elevation sample does not pick up the data.  This is for the user to fix.  But you see the methodology.
14:00: I also mess up the right bank because the end points are not in the same grid element.
15:50:  Is this comment correct?  I think it is.
16:30 Note that your checks pick up the error on the 3rd segment.  
17:00 is the next error message.  In this case, the warning is vague.  It is obvious that the 2nd segment is the problem but we should be able to identify that in the error message.

Here is a project.  You'll need to reset the errors to test it.
https://flo-2d.sharefile.com/d-sde75154a3bd64e1e8a21ec1be17faee7

**Comment by rpachaly** [comment]
Note: Get the saving signal on the channel layers and pop the data on the comboboxes So, both save buttons (QGIS & Cross Section Editor) will pop the data on the editor.

**Comment by FLO-2DKaren** [comment]
> Note: Get the saving signal on the channel layers and pop the data on the comboboxes So, both save buttons (QGIS & Cross Section Editor) will pop the data on the editor.

It's OK to use either button?  I think it is ok after multiple hours of testing.

**Comment by rpachaly** [comment]
I'm not totally sure. I'll check that and, if not, I'll make both buttons to work.

**Comment by rpachaly** [comment]
13:00 min

I changed the message a little bit to specify the right bank ID(s)
 
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/f9d01cb6-a8a2-45db-a024-7d503680a382)

And the first problematic right bank will be selected and zoomed to facilitate the fix by the user
 
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/3eb04a92-30e6-4fcf-a0d1-2b7821b77452)

Finally, added the error message to the log

14:00 min:

Added the error message to the log and zoom to the first problematic cross section
 
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/8db5d664-5d50-469a-8491-3c9ba096c11b)

15:50 min:

It does not matter which save button is being used. Both populate data to the editor. 

17:00 min:

The FID was added to the message

Opinion: When we face these errors, it is better to stop the schematize channel and clear the added data. So, the user must fix everything before running FLO-2D. Otherwise, the error will propagate and FLO-2D will not run properly. 

Done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/commit/57d73fc124a0b9c6c36401b686b4c69eed1c100e

**Comment by FLO-2DKaren** [comment]
OK this seems to be working good.  I did get a bit of a hiccup when I reset my project but reloading the project sorted it out.  I was getting a right bank schema error for FID = 0.  I'll close this issue untill the error happens again.
