### ISSUE TITLE
Busy Cursor

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1224]
The busy cursor stays on when the error message appears.  

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/c502ecee-e61d-4815-9773-6a08310608e7

**Comment by rpachaly** [comment]
Done on 92e3c94128a98c4411cb7351b5154ca04c0440ed

Karen, sometimes the wait cursor stays while the error message is being shown, but when the close button is clicked it restores to the correct cursor. This happens when we have a nested function with multiple try/except blocks. I'm trying to catch all cursor related bugs, but it is tricky.

**Comment by rpachaly** [comment]
Btw, let me fix all the channel errors before merging the https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/compare/master...channel-editor-bugs

**Comment by FLO-2DKaren** [comment]
OK I thought you might want to wait in case your local branch was different.  I am OK with waiting.  I feel the master branch is very easy to swap out with local branches right now.  We aren't so badly divergent anymore.

The wait cursor is annoying but it's not new.  Thanks for trying to sort it out.

**Comment by FLO-2DKaren** [comment]
I'll close this cursor one.  I'll post new ones to new issues.
