### ISSUE TITLE
Storm Drain: 'From Inlet' and 'To Outlet' not auto-assigned when they are '?'

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1291]
Review this situation:

- 'From Inlet' and 'To Outlet' is left blank in **Select components from shapefile** (for Conduits, Pumps, Orifices, and/or Weirs).
- '?' is assigned to _conduit_inlet_ and _conduit_outlet_ attributes (for Conduits, similarly for the other links).
-
![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/5022fcf2-7d11-4789-a5c3-1f744bd9b045)

- **Auto-assign link nodes** button doesn't assign a value to them.

![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/57212fd9-bf80-4dfa-a844-e915572cd662)

**Comment by FLO-2DKaren** [comment]
Hi JJ,

This would mean more work but if you want you can eliminate those "in" "out" fields simply set the attribute to "?".

Then when you assign nodes, your other logic still works.

The problem is that if you don't fill those fields there's an error message but we haven't needed those in several years.

I just set those fields to fid on real projects.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/ee30d8bb-1c2b-4ce9-b3b8-a20d3dc56775)

**Comment by FLO-2DJJ** [comment]
This is an aside check. I just want to know the logic behind the **Auto-assign link nodes** for those "?" nodes. It seems that some are solved but others not. Don't worry about the work.

**Comment by FLO-2DJJ** [comment]
Fixes #1291
