### ISSUE TITLE
GreenAmpt Global vs Spatial Issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1312]
Hi Robson, 
I want to change some of our global variables but I want your opinion on my interpretation of what is going on with DTHETA and POROS.

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/d730cd55-b5f5-49c8-8ef3-048af6e6b609

**Comment by FLO-2DKaren** [comment]
https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/4a8e4257-69d9-465a-8053-cc7da5db165c

**Comment by rpachaly** [comment]
From my understanding of the DIM, it has two methods: 

1. SOIL MOISTURE DEFICIT -> the amount of water needed to bring the soil moisture content back to field capacity

Defined as (SATF-SATI) when the POROS != 0. In this case, set the global POROS to a value different than 0 and on the floodplain element the DTHETA represents the soil moisture deficit (SATF-SATI). **Probably**, FLO-2D engine calculates the volumetric soil moisture - (SATF-SATI)*POROS - internally.

2. VOLUMETRIC SOIL MOISTURE -> the volume of water per unit volume of soil.

Defined as (SATF-SATI)*POROS when the POROS == 0. In this case, set the global POROS to 0 because the floodplain DTHETA already represents the volumetric soil moisture  - (SATF-SATI)*POROS -  and, because of this pre-calculation, it should be in the range of 0.0-0.5. 

So, I agree with you that it does make sense to multiply a global parameters by a spatial parameter. It makes more sense to set the POROS to zero and use directly the volumetric soil moisture (dtheta) in each grid element. 

For me, applying the soil moisture deficiency method only makes sense if the POROS is a spatial parameter multiplied in each floodplain grid element.

**Comment by FLO-2DKaren** [comment]
OK good.  If you already implemented the default to 0.0 and the soil depth to 10, we can close this issue.

**Comment by rpachaly** [comment]
I'll do it in a sec.

**Comment by rpachaly** [comment]
Done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1324

If data was already set on the gpkg, it will use the data on the gpkg. To test it, a new project must be created.
