### ISSUE TITLE
Storm Drain Shapefile Field Select

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1320]
Hi JJ,

I modified the Storm Drain Shapefile UI file so it was aligned a little better. Can you update it?

I also wanted some feedback on that Ponded Area field.  I assume it is disabled.  Maybe we should Grey it out.  See Video

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/338a8a61-88f9-4a59-8ae0-6d6f5f357546

[storm_drain_shapefile.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/15309774/storm_drain_shapefile.zip)

**Comment by FLO-2DNoemi** [comment]
Hi everyone,

We should get rid of the ponded area.

The plugin should be able to read a file with the ponded area, we do not
need this data but the plugin should be able to read an inp that includes
this data, and the plugin should be able to write the INP including the
ponded area columns, it must be zero for all cases and features. We need to
be able to read an inp file with ponded areas and write an inp file
including ponded areas columns because they are needed for compatibility
with EPA SWMMGUI.

In other words, we do not use this feature because this is a completely
wrong simplification that EPA SWMM uses. I thought we discussed this weeks
ago but I may be wrong.

[JUNCTIONS]
;;               Invert     Max.       Init.      Surcharge  *Ponded*
;;Name           Elev.      Depth      Depth      Depth     * Area    *
;;-------------- ---------- ---------- ---------- ---------- ----------
J1-36-30-29-A    1395.80    4.20       0.00       0.00       0.00
I2-36-30-71      1397.00    2.20       0.00       0.00       0.00
I2-36-30-41      1390.40    5.50       0.00       0.00       0.00
I2-36-30-46      1397.40    5.00       0.00       0.00       0.00
I2-36-30-39      1387.20    4.20       0.00       0.00       0.00
I2-36-31-37      1407.70    6.30       0.00       0.00       0.00

[STORAGE]
;;               Invert   Max.     Init.    Storage    Curve
      * Ponded   *Evap.
;;Name           Elev.    Depth    Depth    Curve      Params
  *    Area *    Frac.    Infiltration Parameters
;;-------------- -------- -------- -------- ---------- -------- --------
-------- -------- -------- -----------------------
I5-38-30-5       1420.55  5.10     50       FUNCTIONAL 1000     0        0
       40       40       10       20       30

We can have a meeting if a discussion is needed.
Noemi

**Comment by FLO-2DNoemi** [comment]
We are getting ready to submit the plugin to FCD this week. I would like to
submit a plugin with no ponded area hanging out, this has been an issue for
a long time.

**Comment by FLO-2DJJ** [comment]
Hi @FLO-2DKaren,

You said:

> I also wanted some feedback on that Ponded Area field. I assume it is disabled. Maybe we should Grey it out.

I think you are using an old **strorm_drain_shapefile.ui**

The current one doesn't have _ponded area_:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/cf303d28-bb36-4f70-926d-b59d5994b7a1)

**Comment by FLO-2DNoemi** [comment]
@Karen OBrien ***@***.***>

Once you check the latest version if the ponded area is still there, then
we need to remove it, do not grey it out, that is confusing for users.

**Comment by FLO-2DJJ** [comment]
Hi @FLO-2DKaren and @FLO-2DNoemi,

Please check the current master. The ponded area was eliminated 3 days ago with issue #1229, and pull request #1307

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 

JJ, I think I got that UI file from an old zipped file.  I opened by searching ui instead of loading the plugin window.

Which sucks because it was a pain in the neck to fix those dialog boxes.  But I can do it again on the new window.  I'm going to close this issue.
