### ISSUE TITLE
Discharge plots (nodes) for entire SD system

### ISSUE THREAD

**Issue by FLO-2DNoemi** [FLO-2DSoftware/qgis-flo-2d-plugin#1576]
@rpachaly @FLO-2DKaren 

This is not critical because the GDS is still working and creating the plots but eventually we need to add this to the plugin. 

Add a function to the plugin to generate discharge plots for all SD nodes by selecting the RPT file similar to the current functionality from GDS PRO (see image below). 

The storm drain discharge plots should be saved in a folder within the project. To keep each set of output files organized, include the date and time in the folder name, ensuring a unique folder for future outputs.

![image](https://github.com/user-attachments/assets/409f72d1-135b-4740-b9b6-a81eb3d4e7eb)

**Comment by rpachaly** [comment]
Hi Noemi, check this out:


https://github.com/user-attachments/assets/66dadb62-83da-4134-b0b7-67ca7ab2b1ae

**Comment by FLO-2DNoemi** [comment]
Oops, my bad, I missed this.

This looks great!  I will review it and get back to you with my feedback.

Thanks, Robson!
N

**Comment by FLO-2DKaren** [comment]
So at this time, I would still use GDS for a project like North Peoria because I tried to use MapCrafter on North Mesa and it was too slow.  I'm not going to reopen this comment because I already have an issue posted on MapCrafter to replace swmmio with a better processor.  I think we can do this way faster with numpy or hdf5 or some other system.  I think swmmio is probably using some pad processing mechanics and that's why its so slow.

**Comment by FLO-2DNoemi** [comment]
I agree with you.
