### ISSUE TITLE
Structure name vs number

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1578]
When i load the structure results, the title of the hydrograph is a number.  I think it should be a name.

https://github.com/user-attachments/assets/2acd37b1-0a27-4b6f-b4cb-dc45f5eb5807

**Comment by rpachaly** [comment]
I changed the number to the name when clicking on the map and on the plot. I did not populate the structure on the widget because usually it triggers other stuff. So, to avoid bugs I did not populate the structure on the widget. 

![image](https://github.com/user-attachments/assets/34fc3830-e028-4933-926d-9999df443d86)

Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1583

**Comment by FLO-2DKaren** [comment]
It's easy enough to change buttons  to get the widgets to populate.

**Comment by FLO-2DKaren** [comment]
Tested
