### ISSUE TITLE
Python 3.9 update

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#766]
Update the plugin so that it can load into the latest QGIS.
We will need this to be online so our people can use the Mesh tool and QGIS 3.20...

**Comment by ldebek** [comment]
Hi @FLO-2DKaren I managed to run FLO-2D plugin on QGIS 3.22 with Python 3.9. I had to update `pyqtgraph` package to the version 0.11.1 (previous version 0.10.0 doesn't work with Python 3.9), which required few code adjustments in the drawing plots logic as well. [Here ](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/776)is the PR with those changes.
![image](https://user-images.githubusercontent.com/11883222/143587454-7858e0ff-af5f-4d60-b137-92e921c7ca5f.png)

In terms of issues with HDF5 support - you shouldn't have any if you install: HDF 1.10.7-7 and h5py 2.10.0-2 from OSGeo4W installer. Just make sure that you don't have any different versions of this libraries installed somewhere in your system. If you do then you might get  h5py import errors, which can be fixed by removing previously installed h5py versions.
![image](https://user-images.githubusercontent.com/11883222/143588174-62a14868-8b53-409f-9295-cda7e5ac8b52.png)
