### ISSUE TITLE
RAINCELL Development

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#790]
Raincell sampling - remove zero rainfall lines from raincell.dat. (See it with Nate)
Set 16 bit float variables to reduce file size?

These are related or duplicated: https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/777, https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/790, https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/819, https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/820

**Comment by FLO-2DNoemi** [comment]
@FLO-2DKaren some comments below:

Raincell sampling - remove zero rainfall lines from raincell.dat. Update FLOPRO.exe accordingly.
Set 16 bit float variables to reduce file size? Change to 4 decimals instead of 6.
We need to keep raincell.hdf5 with fix size. Array from 1 to IRINTERS, 1 to NNOD.
Create data files for the alternative methodology:  FLO2DRainCell.DAT and RainCellRaw.dat.

**Comment by FLO-2DKaren** [comment]
Closing this refer to #777
