### ISSUE TITLE
Rearrange user interfaces for writing of RAIN.DAT, RAINCELL.DAT and binary HDF

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#820]
To accomplish this explore the different combinations of checkboxes, buttons, existence of rain layers, CONT.DAT dialog, rain Editor widget, etc.

These are related or duplicated: https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/777, https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/790, https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/819, https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/820

**Comment by FLO-2DNoemi** [comment]
@Juan Jose Rodriguez ***@***.***> we do not really need to change the
RAIN.DAT file.

The idea is to create the RAINCELL.DAT or RAINCELL.HDF5 separately from the
DATA Files Export option.

Now the RAINCELL.DAT is always created when you export the DAT files, this
file is huge and many times the user does not need it because the
RAINCELL.HDF5 is the file that is used.

**Comment by FLO-2DKaren** [comment]
complete
