### ISSUE TITLE
Tailing Dam Tool

### ISSUE THREAD

**Issue by FLO-2DNoemi** [FLO-2DSoftware/qgis-flo-2d-plugin#873]
@FLO-2DJJ 

- [x] Add option to enter multiple inflow elements to the tailing dam tool. New option to create INFLOW.DAT with the volume distributed between one or more elements.
- [x] Review total volume.
- [x] Compare a final run User Volume to Summary.out Volume.  They seemed off to me. (karen)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ I have an idea for this method.  If you use a polyline to create an inflow node, it should divide the inflow hydrograph by the number of cells intersected by the line.  The intersection method should be the line that crosses the cell.  

Inflow.dat gets: 

"H Time  Q/#cells   Cv"

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ, @FLO-2DNoemi 

Hi JJ,  

I've been working with the tailings dam tool and I understand how it works now.  Can we have a meeting about some ideas I have for it?  Not in a hurry for the meeting.

1. Use a checkbox on the inflow.dat form that identifies that we only want the hydrograph data not the inflow.dat file.  
2. Have tailings dam tool export tab delimited hydrograph.
3. We can copy that into qgis for a polyline.
4. Any grid element that intersects the polyline will get the inflow hydrograph divided by the number of cells in the intersection.
5. That hydrograph can be saved into it's own space in the 

I also have 2 ideas for the tailings dam too.
1. Let the user change the User volume on the final form.
2. Can we save the data on the final form so that when we open it, we don't have to add all of the grid elements again.
3. Can we have a comparison mode that exports inflow.dat for all of the  different conditions in the final form.  That way, I could run and compare the different hydrograph shapes and the different sediment concentration shapes.

**Comment by FLO-2DJJ** [comment]
> * [x]  Remove the single space to enter the grid cell number
Done

**Comment by FLO-2DJJ** [comment]
The following Tailings Dam Breach executable accounts for the tasks checkboxed in the comments of this issue. Please test it and replace the current executable.
 
[Tailings Dam Breach.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/11837095/Tailings.Dam.Breach.zip)

In the near future let's have a meeting to review  @FLO-2DKaren 's ideas (in her comment above -June 20th).

**Comment by FLO-2DNoemi** [comment]
@Juan Jose Rodriguez ***@***.***>

These enhancements are good, we can review this list carefully and work on
it. I know you are working on other things that are a priority so let's
keep this on the top lof things to do and start it  whenever you have time.

**Comment by FLO-2DNoemi** [comment]
Enhance Tailing dam tool: 

- [ ] CDA additional equation.
- [ ] Make the user volume editable when you open the inflow data tab ( last page of tool) .
- [ ] Save the inflow.dat data page in the xml file. Save inflow nodes, patterns and other data. For example: the user don't have to add all of the grid elements again.
- [ ] Let the user change the User volume on the final form.
- [ ] Create a comparison mode that exports inflow hydrographs (INFLOW.DAT) for all of the different conditions in the final page. That way, a user can run and compare the different hydrograph shapes and the different sediment concentration shapes.

@FLO-2DJJ please review the list.
