### ISSUE TITLE
Debug Path Issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#876]
@FLO-2DJJ 

Hi JJ,  I found an issue with loading the debug **Issues Files**.  This system uses the LastGdsDir as the path.  I think it is breaking when that path does not equal the Debug path.  

File:  dlg_issues.py
Line: 808 

I think you can fix this by using the Last Debug directory instead of the lastGdsDir.

Here's a video to show how the bug.

https://flo-2d.sharefile.com/d-sfe59c05a5a3b4a2ab11bd097833f53b4

**Comment by FLO-2DJJ** [comment]
@Karen OBrien ***@***.***> The problem seems to be that the
"FLO-2D/lastDEBUGDir" setting was wrongly assigned to the whole path +
filename. I changed it to the path only:
line 227:
s.setValue("FLO-2D/lastDEBUGDir", os.path.dirname(debug_file))

 Try it and tell me if that solves the problem. Already uploaded to GitHub.

I'm working on the other issues in the debug functionality.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 

I have 1 final suggestion for this.  When you click Debug Run, close this dialog box too.  It stays open and you have to click cancel to close it.  it's confusing.

![image](https://user-images.githubusercontent.com/20424460/197272950-5f3e31f3-924e-4198-9937-6b09845f839e.png)

**Comment by FLO-2DJJ** [comment]
Fixed. @FLO-2DKaren, @FLO-2DNoemi please test it and report to close issue.
