### ISSUE TITLE
Reading Tailings Dam Breach files: error in assignment of units

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#882]
Look at the sequence of several readings and changes of units. At some point the units are wrong.

**Comment by FLO-2DNoemi** [comment]
@FLO-2DJJ 

The issue is only with metric units, and the problem is that the information that a file is using metric units is not save in the XML. When the XML is reopened, then the tool used English units as the default unit.

The following steps show the issue:

1. Create an XML file and save it using metric units.
2. Close the Tool
3. Open the tool and load the XML file

If you try to change the units to metric the tool recalculates the data applying the conversion factors from English to Metric.

**Comment by FLO-2DJJ** [comment]
@FLO-2DNoemi. The units used are not saved in the XML file, I see two ways to fix this:

1. Leave the XMF as it is and ask the units to use when opening the file.
2. Save the units in the XMF file.

What do you think @FLO-2DNoemi ?

**Comment by FLO-2DNoemi** [comment]
@Juan Jose Rodriguez ***@***.***>

I think we should save the units in the XMF file.

**Comment by FLO-2DNoemi** [comment]
Thanks. I will review this and get back to you.

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi 
Does this mean an update to the Tailings Dam Tool?

**Comment by FLO-2DNoemi** [comment]
Yes, only the executable.  Data with metric units were not being loaded
correctly. I will send it your way.
