### ISSUE TITLE
Timeseries output file path

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#918]
@FLO-2DJJ 

- [x] Hi JJ,  This is the path of the time series file.

![image](https://user-images.githubusercontent.com/20424460/230735055-636b6333-0a06-4585-b913-b1d6cef2b018.png)

But swmm.inp has this:
;TimeSeriesImportFileTest
TimeS1           FILE       "C:\Users\Public\Documents\FLO-2D PRO Documentation\Example Projects\QGIS Tutorials\QGIS Lesson 3\QGIS Lesson 3 Export\TimeSeriesTable.txt"

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi 
Hi Noemi,
The swmm error message in the swmm.rpt file is incorrect.  It should say something about not finding the file.
![image](https://user-images.githubusercontent.com/20424460/230735365-07e713e9-39dd-4677-984d-9b583094d1cf.png)

Also, the error code in stormdrainerror.chk is not the same as the error in swmm.rpt.
![image](https://user-images.githubusercontent.com/20424460/230735425-3ce3428b-1f98-447d-8f8e-0a8b30f8a19f.png)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ @FLO-2DNoemi 

Hi JJ and Noemi,

We need to make these options editable.  Right now QGIS exports the Current Date and Time.  So the date/time dependant data doesn't work beecause the user cannot set the time in the simulation.
![image](https://user-images.githubusercontent.com/20424460/230735867-1172e049-f5bb-4732-bf32-3ed31666ef86.png)

**Comment by FLO-2DNoemi** [comment]
Hi Karen and JJ,

Let's think about this twice before we move forward.  We can make the date
an time editable, this will not generate an issue running FLOPRO.exe,
because the time is hardwire in the storm drain model, in others words we
use the simulation time from CON.DAT, we add it to the start date and start
time from inp and internally calculates the end date and time for the storm
drain layer. In this way we make sure the time is always controlled by the
surface layer and the user only needs to worry about the CON.DAT time.

Now that we want to change this, we need to think about the time
synchronization between the two layers (surface and storm drain), and
the CONTROL DATA from inp and the timeseries files. We need to be careful
or we can end up creating other issues when we use the time from two
different data files. If we make this editable, the user will need to enter
time in CON.DAT file and in INP file, and the inp data has to be always
synchronized with any time series that is created.  This does not simplify
the model implementation but makes this more difficult. Is there a better
way to simplify this and make it simple? Let's think about it.

The main reason we need these lines (date and time, not the values) in the
INP file is that the user can open the data/results in the SWMM GUI.

Let's take a look at this together so we can decide how to proceed.

Noemi

**Comment by FLO-2DNoemi** [comment]
@FLO-2DJJ after our meeting today, I think we should do the following:

1) Make the Date and Time options editable but keeps the default value that is now calculated by the plugin, using the current date and the simulation time from Control dialog (CON.DAT).  This will be good enough for the SD projects that do not use timeseries. In other words, the user will not need to add any change to the date and time but if something is changed, it will work anyway.

2) When INP is saved, check that date from INP is synchronized with the timeseries date, only if timeseries exists in the project. If they are not synchronized, display a warning, only for this case, no warning is needed if they are synchronized.

3) Add a note (not always visible), that is only show when the user move the cursor over the dates and times to enter new values, explaining the synchronization of time. See image below:

![image](https://user-images.githubusercontent.com/20424558/232158246-471253c8-941c-4f4c-98c3-04ed28d0f243.png)

@FLO-2DKaren  please take a look at this and let us know if you have comments.

Noemi

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren and @FLO-2DNoemi
Please review the plugin in the pending pull request in GitHub and close this issue if satisfied.

**Comment by FLO-2DKaren** [comment]
Complete

**Comment by FLO-2DJJ** [comment]
Make time series group [TIMESERIES] of SWMM.INP as in EPA SWMM: 

- time series files in same directory of project have no path (only the file name). For example:
                 ThaliaStage      FILE       "ThaliaCreekStage_2017.dat"
- time series files in a different directory include path (and file name).
                THALIA2222       FILE       "C:\TRACKS\PROJECTS\FLO2D\QGIS\2023\SD Pumps\TS.DAT"
