### ISSUE TITLE
RainArf import

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#928]
When rain.dat is imported, it builds individual polygons for each grid element.  This is very slow and not necessary.  
Limit the import from *DAT files to the raincell table not the raincell areas.  

Leave the raincell layer in place.  We can repurpose it later.

**Comment by FLO-2DKaren** [comment]
All rain arf are imported into the Rain Arf Areas layer.  That is a vector layer.   That data is not needed in a Vector Format.  it is only needed in a Table.  So this job is to import the data into the table only.



![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/a276788e-e6aa-4692-bb51-791aeaacbb29)

**Comment by FLO-2DKaren** [comment]
When you import, write the data to the table not the vector layer.


![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/e473d843-cb33-4d90-b98b-508c8cc8f1b2)

**Comment by FLO-2DKaren** [comment]
The import will be similar to the import for the SCS infiltration data.


![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/f3152cba-a89e-4d05-b2d4-5efcc1d57ec4)

**Comment by FLO-2DKaren** [comment]
Here is the key word search for the rain_arf_areas

Search "rain_arf_areas" (19 hits in 5 files of 400 searched)
  C:\Users\Alejandro Riano\PycharmProjects\qgis-flo-2d-plugin\flo2d\db_structure.sql (8 hits)
	Line  444: CREATE TABLE "rain_arf_areas" (
	Line  450: INSERT INTO gpkg_contents (table_name, data_type, srs_id) VALUES ('rain_arf_areas', 'features', 4326);
	Line  451: SELECT gpkgAddGeometryColumn('rain_arf_areas', 'geom', 'POLYGON', 0, 0, 0);
	Line  452: SELECT gpkgAddGeometryTriggers('rain_arf_areas', 'geom');
	Line  453: -- SELECT gpkgAddSpatialIndex('rain_arf_areas', 'geom');
	Line  464: --    AFTER INSERT ON "rain_arf_areas"
	Line  474: --    AFTER UPDATE ON "rain_arf_areas"
	Line  484: --    AFTER DELETE ON "rain_arf_areas"
  C:\Users\Alejandro Riano\PycharmProjects\qgis-flo-2d-plugin\flo2d\db_triggers.sql (3 hits)
	Line  88:     AFTER INSERT ON "rain_arf_areas"
	Line  98:     AFTER UPDATE ON "rain_arf_areas"
	Line 108:     AFTER DELETE ON "rain_arf_areas"
  C:\Users\Alejandro Riano\PycharmProjects\qgis-flo-2d-plugin\flo2d\flo2d.py (2 hits)
	Line 1217:                         "rain_arf_areas",
	Line 1481:                     "rain_arf_areas",
  C:\Users\Alejandro Riano\PycharmProjects\qgis-flo-2d-plugin\flo2d\flo2d_ie\flo2dgeopackage.py (2 hits)
	Line  486:             """INSERT INTO rain_arf_areas (rain_fid, arf, geom) VALUES""",
	Line  496:             "rain_arf_areas",
  C:\Users\Alejandro Riano\PycharmProjects\qgis-flo-2d-plugin\flo2d\layers.py (4 hits)
	Line  242:                 #     "rain_arf_areas",
	Line  246:                 #         "styles": ["rain_arf_areas.qml"],
	Line  462:                     "rain_arf_areas",
	Line  466:                         "styles": ["rain_arf_areas.qml"],
Search "rain_aft_areas" (0 hits in 0 files of 400 searched)

**Comment by rpachaly** [comment]
At this point, I did the following:
1. Not loading the Rain ARF areas vector layer to the canvas
2. Not writing data to the rain_arf_areas in the geopackage 

Two questions arise:
1. Is this supposed to work only with importing the .DAT files or is it supposed to work with all import methods? If so, can you provide me one .hd5 file? I'm asking this because the import_rain method is called by all import methods on the plugin. 
2. Should I remove the creation of the rain_arf_areas vector layer on the database? Or only not writing to the table is enough?

**Comment by FLO-2DKaren** [comment]
@rpachaly 

Answers:
1. This should work with the spatial data in Rain.DAT only.  
    It has nothing to do with RAINCELL.DAT or RAINCELL.hdf5
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/b1ec43ee-f195-461e-8ea2-92f985e9494c)

2. I think it is OK to remove the rain_arf_areas vector layer from the database.

**Comment by FLO-2DKaren** [comment]
raincell.hdf5 is generated by the realtime rainfall process.  You can try to complete Lesson 5 to get a sample of that data.

I would really appreciate it if you finished Lesson 5.  It is actually very helpful for you to understand the realtime rainfall data processing tool.    

You might find that you get a missing h5py error.  You can add that module with the OSGEO4W installer.  Just search for hdf5, and h5py.  You can add both of them.

**Comment by FLO-2DKaren** [comment]
I'd like you to perform the testing before you hand it off to me.  Not only will it help you understand FLO-2D Rainfall better but it will also give you insight on the difference between *.DAT files and the GPKG.  You might not realize this but the FLOPRO.EXE doesn't use the gpkg to process data.  

**Testing Process**

1. Complete Lesson 1 Part1, 2, and 3.  Export and run the model.  Then save a copy of rain.dat so we can review it.
2. Build a blank geopackage and Import the model you just exported.
3. Export that model again and compare the RAIN.DAT from both conditions.  NOTEPAD++ has an excellent compare plugin.
4. Run Lesson 5 and we'll make sure that the raincell.dat hasn't changed either.

Then I'll merge your code and repeat the test on my end.  I think that should be plenty of testing.  

6.

**Comment by rpachaly** [comment]
Hi!

I removed the rain_arf_areas from the geopackage and all code related to this vector layer. The data is only written to the raincell_data table now. 

I have completed the testing process, and everything is working. Since now there is no rain_arf_areas in a new geopackage and to ensure thorough testing, I introduced an additional step by rerunning the entire testing process using an old .gpkg file that contains the rain_arf_areas vector layer. This was done to confirm that no issues arise.

However, I'm facing some issues on the MASTER branch (prior to these modifications). When I export a project that has Realtime Rainfall using the Export GDS files, the RAINCELL.DAT is not exported. I've to manually export it using the Export Realtime Rainfall  button and it works. Also, I've installed the hdf5 and h5py using the OSGeo4W installer and when I try to export the Realtime Rainfall using the hdf5 format it results in an error and does not export the file. I'm going to push this branch since these two issues are occurring on the master branch and have no relation with the modifications that I've made.

**Comment by FLO-2DKaren** [comment]
I just need to confirm that you are writing to the rain_arf_cells not the raincell_data.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/59857fe7-4319-46c5-82a9-ee7d74842474)

Let's do a meeting and see if we can sort out the other issue you are having.
It's probably OK to push your branch for now.  I agree that the other issue has nothing to do with your code.

**Comment by rpachaly** [comment]
Yes, it is writing to the rain_arf_cells. It was supposed to be rain_arf_cells instead of raincell_data on the previous comment. My bad.

Can we have this meeting around 5:30 PM your time today?

**Comment by rpachaly** [comment]
In two places the rain_arf_areas was not removed. When I try to import from hdf5 file I'm getting this error. I'm preparing a branch to solve this issue.

**Comment by FLO-2DKaren** [comment]
OK thanks.  I will add this to my import export test list.  I forgot about it so good catch.
