### ISSUE TITLE
Raincell.hdf5 compression

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#955]
I don't think compression is being applied to the raincell.hdf5.  Let's see test a few different compression options to see how the read, write, and flopro.exe responds to raincell.hdf5 compression.

**Comment by rpachaly** [comment]
I've got this error when using the "gzip" and "lzf" compressions:
"typeerror: scalar datasets don't support chunk/filter options"
Same happens when using chunks=True. 

There is a library called hdf5plugin that allows for additional HDF5 compression filters.

**Comment by FLO-2DKaren** [comment]
@rpachaly 

I don't know much about hdf5 code but is it possible that the compression can only be applied to the arrays.  Maybe you are trying to apply it to the wrong part of the data?

Because a scalar dataset only has one element so you can't compress it.  Can you apply the compression to separate tables?

**Comment by rpachaly** [comment]
@FLO-2DKaren 

Good point! I applied to the array table (IRAINDUM) and it looks like it is working. Using the gzip compression, it reduced the file size from 122 mb to 1 mb. I'll run some tests here to evaluate the other compressions and to see how flopro.exe responds to compression.

**Comment by FLO-2DKaren** [comment]
@rpachaly 
Robson, That's sweet.  

You guys, I'm embarrassed to say that I totally forgot what a scalar property was!!!  haha, I had to Google it.

@FLO-2DNoemi 
Noemi,  
Robson figured out HDF5 compression on the raincell.hdf5.  When you are ready to try it on Fortran, be aware that you cannot apply it to scalar elements of the hdf5 file.  You can only use it on tables with arrays.  I bet it is not good for small data either.  It should be applied to the big tables only.  So that means skipping things like hystruct control data or rainfall time series.

We should test how the Model Initialization Time responds to the compressed raincell.hdf5 file.  I think it will be take time to extract that data before it can be applied to FLO-2D.   We might test it with different compression levels.

Noemi, 
You should also see what sort of compression you are using on timdep.out.  Since that code is already set up, you could easily test it and I could test if it slows down the mesh import.

**Comment by FLO-2DNoemi** [comment]
Hi Karen,

It is a good idea to test it with TIMDEP.HDF5. I will let you know what
I find out.

Noemi

**Comment by FLO-2DKaren** [comment]
Lesson 1
Rain.dat will look different
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/f7ab5ab2-82da-44dc-a11f-78d60d94bf4d)

CONT.DAT should look something like this:
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/0c762c98-a245-4a8b-ac3c-b5b40672acea)

Project run should look like this:
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/b3729dfd-6194-43f2-8693-22ab1084eca8)

**Comment by FLO-2DKaren** [comment]
3 Tests
Run lesson 5 with raincell.dat
Run lesson 5 with raincell.hdf5
Run lesson 5 with compressed raincell.hdf5

Karen - Run North Mesa

**Comment by rpachaly** [comment]
When I run the simulation using the raincell.dat I get a Rainfall volume of 248.798 but when I run with the raincell hdf5 - compressed or not - it shows a Rainfall volume of 0 (SUMMARY.OUT). I set the CONT.DAT and RAIN.DAT exactly as you requested for all three projects. Can you check that?

**Comment by FLO-2DKaren** [comment]
@rpachaly  OK I'll test it right now.

**Comment by FLO-2DKaren** [comment]
Does your hdf5 have values in the rainfall field?

**Comment by rpachaly** [comment]
Yes, on the IRAINDUM table

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/a1c7b2c6-3d79-4ace-acd6-0df4b563626f)

**Comment by FLO-2DKaren** [comment]
OK I still can't get the hdf5 to export.  Can you send me yours?

**Comment by rpachaly** [comment]
[RAINCELL.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/11750664/RAINCELL.zip)

This raincell.hdf5 is not compressed.

**Comment by FLO-2DKaren** [comment]
I concur.  No rainfall is happening.  I think this might be due to the hdf5 version.  FLOPRO.EXE uses 1.8.11 and this one is made with 1.14.  I know that was a problem in the past.

**Comment by FLO-2DNoemi** [comment]
I have the HDF5, if you send me the dat files, I can run it in debug mode
and check.

**Comment by rpachaly** [comment]
[dat_files.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/11750843/dat_files.zip)

**Comment by FLO-2DKaren** [comment]
It is calculating the raincell.chk file
    Average grid element rainfall for the entire storm=      2.6605
    GRID      TOTAL RAINFALL
        1            2.5858
        2            2.5858
        3            2.5858
        4            2.5858
        5            2.5858
        6            2.5858
        7            2.5858
        8            2.5858
        9            2.5858
       10            2.5858
       11            2.5858
       12            2.5858
       13            2.5858

**Comment by FLO-2DNoemi** [comment]
The conversion to hours of the time interval for the real time rainfall was
out of place. The data is read from the HDF5 file without issues.  Try the
executable inside the folder. I run the example using the rainfall from the
HDF5 file.

https://flo-2d.sharefile.com/d-s406589536c2f40c7897684a7d51181ca

Let me know if you have any comments.

**Comment by rpachaly** [comment]
The new flo-2d executable worked just fine. 

**Lesson 5 results:**
There is a difference between the .dat and .hdf5 output files. This is probably due to a slightly difference on the reported simulation time and average time step. The depth difference happens only on the third or fourth decimal place. Please, take a look on the summary and depth files that I uploaded. In my opinion, I don't believe that this difference has significant impact on the results and the file size reduction is substantial. It is important to highlight that the hdf5 and hdf5 compressed have the exact same results except for the computer run time. However, to really evaluate the differences between the compressed and uncompressed hdf5 file in terms of computer run time, the simulation must be running exactly on the same conditions. This did not happen on my machine while I was running the simulations. I can rerun the simulations in the same conditions if you want.

[hdf5_comparison.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/11763465/hdf5_comparison.zip)

**Big model results:**
The computational domain has around 2.5 million cells, the .gpkg has around 15 gb, and raincell.dat has 11.2 gb. I was not able to export to hdf5 – both compressed or not, or using the chunks=True or not. I’m getting a memory error. It is weird because I was able to export the raincell.dat without any issues. I need to explore it a little bit more, but it seems to be related to fetching the query data. Here is the python error:

> File "C:\Users/robso/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\rain_editor_widget.py", line 247, in export_rainfall_to_binary_hdf5
              data = self.gutils.execute(qry_data).fetchall()
             MemoryError

**Comment by rpachaly** [comment]
**These are the file sizes for the lesson 5 model:**
raincell.dat: 210 mb
raincell.hdf5: 122 mb
raincell.hdf5 compressed: 1mb

If tomorrow I can solve the big model error when exporting the raincell to hdf5, I'll write down the file sizes here as well.

**Comment by FLO-2DKaren** [comment]
@rpachaly 

Hi Robson,
So we know specific mods like Pandas cause these sort of issues.    I wonder if the h5py has memory related issues.  I think that mod is pretty buggy.  It's worth googling.  Maybe you can use the QGIS hdf5 tools.

Since this is a sql task, you might look into that.  I've seen online that you can do fetchmany().  That might be a way to do this in smaller datasets.  It's a good thing to google too.  But I don't know what the difference is.

If necessary, we can ask Nate.  I'm guessing he's done this sort of thing on even bigger projects.

**Comment by rpachaly** [comment]
@FLO-2DKaren 

Hi Karen, 

The code breaks before entering the hdf processor. So, I think this error is not related to h5py library but to the sql task. This afternoon I'll take a deeper look to see if I can find a solution. Otherwise, we can ask Nate.

**Comment by rpachaly** [comment]
The problem is that it is querying a lot of data before using the hdf processor to create the hdf5 file. 

When you don't have a HUGE amount of data in the raincell table, the algorithm is able to execute the query and store this data in the memory then it uses the hdf processor to create the hdf5 file. 

When you have a HUGE amount of data in the raincell table, the algorithm crashes by memory error. 

I'm finding a solution that, during the querying and using the fetchmany() method, I'm adding data directly to the hdf5 database in chunks. In this way, we can do small queries and add these data in the raincell.hdf5 without any issues. It seems to be a good solution to avoiding storing lots of data in the memory. This can be used in other portions of the code where a lot of data is exported to hdf5 files. 

Also, since we know the shape of the IRAINDUM, we can add a progress bar or something for the user to know how much of the process is completed. What do you think? 

Today, I was able to prepare the data and add it to the hdf5. But it is not adding correctly, I just need a little bit more of time to figure this out.

**Comment by FLO-2DKaren** [comment]
@rpachaly 
I like this idea.  It is a good solution.  Go ahead with the progress bar too.  Those are really helpful.

**Comment by rpachaly** [comment]
@FLO-2DKaren 
Hi Karen!

I was finally able to figure out the export raincell.hdf5 in batches. It took me while, but it is working. I need to do some small adjusts on my code and running a little bit more of tests before pushing the branch for you to test. The progress bar is also working just fine.

However, it made the exporting a little bit slower when we have small datasets. The batch size is based on the number of cells. I believe it is better to run this modification only when we have a significant number of cells. But I need a number, 100,000 cells maybe? 500,000? I don't have too much experience in running the model to estimate a good threshold.

**Comment by FLO-2DKaren** [comment]
@rpachaly 
Just to remind you of our meeting notes.  I don't care if the processor is slow on small projects.  I do not anticipate anyone using this tool on anything smaller than 100k cells.

**Comment by rpachaly** [comment]
I finished some performance tests here:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/a1541992-7ee9-43af-b1c8-75c4c7cf363d)

The **batches plus the compression** increases the computational time to export the hdf5 file significantly. On the other hand, the hdf5 file size gets really smaller.

\* I did not count the time for exporting the .dat file in this model
** I did not run all the exporting, but I estimated based on 2 time intervals that it will take around 8 hours to finish exporting  
*** I'm going to run this overnight because it take a lot of my processor. Tomorrow I'll update this table.

In my opinion, it is worth having this extra time to export the data to get a smaller file. 

I'll push the branch right now.

**Comment by FLO-2DKaren** [comment]
If you want me to do the large model test, I can.  I have a project in that area.

**Comment by FLO-2DNoemi** [comment]
We also need to take into account that compression will increase the time
to read the RAINCELL HDF5 data for FLO-2D. This could increase the
simulation time susbstantially.

**Comment by FLO-2DNoemi** [comment]
That is fine. I need to check the simulation time..

**Comment by FLO-2DKaren** [comment]
Robson,
Push the branch and we can both test it.

**Comment by rpachaly** [comment]
> We also need to take into account that compression will increase the time to read the RAINCELL HDF5 data for FLO-2D. This could increase the simulation time susbstantially.

That's a good point! We need to run a simulation to compare the compression impact on the computer run time. I did not run in exact conditions, but the models that I've ran did not shown significant differences.

**Comment by rpachaly** [comment]
> Robson, Push the branch and we can both test it.

I just pushed the branch.

**Comment by FLO-2DKaren** [comment]
Sweet.  I'll test it on North Mesa.  I'll turn the compression off for one test and on for another test.
Robson,  You can test it when your computer isn't needed or you can wait for me to test it.  Either way, we'll have this information by tomorrow.  I'll add your table to our documentation.

**Comment by rpachaly** [comment]
I'll run this overnight. Then all these tests will be performed on the same conditions. Tomorrow I'll update the table.

**Comment by rpachaly** [comment]
It took 3:53 hours to export the hdf5 file and it has a file size of 30.5 mb for the 2,560,000 cells model.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/9949e12e-8704-44a1-9411-ef57d8cc6f25)

**Comment by FLO-2DKaren** [comment]
@rpachaly 
Hi Robson,  When I try to run the rainfall interpolator, I get an error message.

I'm using QGIS 3.28.7

```
2023-06-23T14:36:23     INFO    Traceback (most recent call last):
              File "C:\Users/Alejandro Riano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\rain_editor_widget.py", line 163, in import_rainfall
              asc_processor = ASCProcessor(grid_lyr, asc_dir) # as_processor, an instance of the ASCProcessor class,
             TypeError: __init__() missing 1 required positional argument: 'iface'
```

I also get this message but I think this message is to valid.
```
2023-06-23T14:36:23     WARNING    FLO-2D : Importing Rainfall Data from ASCII files failed! Please check your input data.
             Is the .RFC file missing?
```

**Comment by FLO-2DKaren** [comment]
Tested on another computer.  Same error.

**Comment by rpachaly** [comment]
@FLO-2DKaren 
Hi Karen, 

There was a missing reference to the iface on the ASCProcessor class. This issue is solved and I pushed the branch. 

I was thinking, maybe a progress bar on this import would be nice. What do you think?

**Comment by FLO-2DKaren** [comment]
@rpachaly 
OK, I'll test it now.

**Comment by FLO-2DKaren** [comment]
I have one running on North Mesa.  I'll check it later and see where it is.  A progress bar would be really handy.

**Comment by rpachaly** [comment]
@FLO-2DKaren 
Hi Karen, 

How was the teston North Mesa? I'll add the progress bar and push the branch again.

**Comment by rpachaly** [comment]
I changed the progress bar to QProgressDialog. This dialog is the same dialog that shows when we run the infiltration. I think it is prettier. I added this to importing raincell and exporting raincel - both hdf5 and dat.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/a154c7bd-2cf9-4707-9133-d6ad4bb79b45)

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/6e8bb627-e29a-4aca-ba42-eb23f13949e7)

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/6499392d-3fc7-4325-a825-815a6d8ec9f2)

* The bar is blue. It changed to grey when I switched to the windows snipping tool but it's working just fine. 

I'm pushing the branch.

**Comment by FLO-2DKaren** [comment]
@rpachaly I'm going to merge the branch.  I didn't get back to my North Mesa Testing but I think we can move on now.  This is way better than it was when we started.  If we run out of things to do, we can consider applying some optimization to the interpolator.

**Comment by FLO-2DKaren** [comment]
From Nate's compression.  No need to change anything.  I just want to have this for future reference.
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/a38c988d-9ab8-4772-8d93-c6af3002f990)

**Comment by FLO-2DKaren** [comment]
My tests for north mesa 2.5 million cells.
Calculate rain took around 2.5 hours to interpolate the rain.
RAINCELL.hdf5 took over 3 hours to export.  It is 16mb

I think we can live with this for now.  I already pushed the code into the new plugin.
