### ISSUE TITLE
Progress Dialog in demanding processes

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#975]
When we have a process that demands a lot of computational effort, QGIS freezes while the process is running. This could lead to a QGIS crash if the users clicks on QGIS. Adding a progress dialog (QProgressDialog) - the same as on the Infiltration editor - will allow the user to understand that there is a long process going on and its current progress. I'm going to add the plugin processes names here and a check box where the progress dialog is needed. 

- Grid Tools
- [x] Create grid
- [x] Sampling grid elevation from raster layer
- [x] Correct grid elevation
- [ ] Boundary Condition Editor - Specifically the Polygon tool is very long to process any project.  I think we can speed it up by a code review.
- [x] Calculate reduction factors
- Initial Condition Editor 
- [ ] Tailings
- Rain Editor
- [X] Export - RealTime Rainfall
- [x] Import - RealTime Rainfall
- [ ] Infiltration Editor - SCS polygon
- [X] Green Ampt
- Multiple Channel Layers are processed automatically when you save the data.  We could add a Progress Bar to that code.

**Comment by FLO-2DKaren** [comment]
Yes this is a good idea but i'm going to list the ones to leave out because they don't typically take long to do.

Profile Tool - This tool is more like a toy at this point so let's skip it for now and reassess it's value once we decide how to make this tool better.
Cross Sections Editor - This one doesn't really take that long even on very big models.
Initial Condition Editor - This one never takes long.
Rain Editor - only apply it to the raster calculator.
Schematized Channels Editor - I'm considering removing this tool.  It's much easier to do this work in a attributes table editor.
Structures Editor - This one is OK but usually doesn't take that long.
Street Editor - don't bother.  
Floodplain Cross Sections Editor - doesn't take long to process.
Storm Drain Editor - Only apply it to the create storm drain from Layers.
Levees and Breach Editor - This editor has issues but processing time isn't one of the issues.
The Multiple Channels editor is only a global value editor and does not have a processing time since it only sets the global values.  There are other processors related to this system that do need a progress bar.  We can discuss them in a meeting.

**Comment by rpachaly** [comment]
Hi Karen, 

I removed the ones that you suggested.

**Comment by rpachaly** [comment]
I pushed a branch with a progress dialog for creating a grid.

**Comment by FLO-2DKaren** [comment]
The create grid progress works good on my side.

**Comment by FLO-2DKaren** [comment]
Can you add a progress bar for this one too?  I think one is there for the area average but not for the point sample.
Low priority.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/5715f945-a97a-4b02-98d2-2a090cff51fb)

**Comment by rpachaly** [comment]
I've added the progress dialog to the functions poly2grid and raster2grid. So, the grid correction and raster elevation will have a progress bar.

**Comment by rpachaly** [comment]
I'm closing this issue. Let's add the progress dialog as we update or add new features. Don't need an specific issue for this anymore.
